# Get from https://domluna.github.io/JuliaFormatter.jl/stable/

indent = 4  # default is 4
margin = 88  # default is 92
always_for_in = true  # default is false
whitespace_typedefs = true  # default is false
whitespace_ops_in_indices = true  # default is false
remove_extra_newlines = true  # default is false
import_to_using = true  # default is false
short_to_long_function_def = false  # default is false
long_to_short_function_def = true  # default is false
always_use_return = true  # default is false
whitespace_in_kwargs = true  # default is true
annotate_untyped_fields_with_any = true  # default is true
format_docstrings = true  # default is false

# align_* = true  # see custom alignment docs

conditional_to_if = false
normalize_line_endings = "unix"
trailing_comma = true
trailing_zero = true
join_lines_based_on_source = false
indent_submodule = true
separate_kwargs_with_semicolon = true
surround_whereop_typeparameters = true
for_in_replacement = "∈"  # Options ares "in", "=" or "∈"
disallow_single_arg_nesting = true

verbose = true

align_matrix = true